### ISSUE TITLE
No clearly defined open source license.

### ISSUE THREAD

**Issue by ncthbrt** [fperucic/treant-js#1]
Hi there. First off, thanks for this great resource, Treant-js is a great looking library. 
Could you please could you clearly define the license it is open sourced as (e.g. lgpl/MIT), not all open source licenses are compatible with one another.

**Comment by fperucic** [comment]
Hi, I appreciate your opinion.
This library is published as open source under the MIT licence.
I will make the change, so MIT licencing is clearly visible in the source.

**Comment by ncthbrt** [comment]
Thank you. :smile:
