### ISSUE TITLE
How can I render different branch with different colors?

### ISSUE THREAD

**Issue by kxxoling** [fperucic/treant-js#103]
I found this great project from Google, and having started a inner project based on it. But now I block on a new feature implementing.

I need to customize branch style based on child node data, eg.

![image](https://user-images.githubusercontent.com/1227139/34869468-f0c170c6-f7c1-11e7-80f7-d30c59361052.png)

This is what I want to implement, but the config of svg stroke is related to the father node as I found on the document. How can I implement the result I want?

**Comment by Xuroth** [comment]
This is something I'm looking into as well. My app allows customization of nodes that gets saved in a JSON array, and I can easily parse and add `.connectors{}` (if present), but that targets all the children of the current node. What I'd like to do is have a way to define the node's connection to it's parent instead. For example, in the image above, the 'Red' node object could have `.parentConnector{}` that defines it's connection to 'Color Switch' is `stroke: 'red'`.

**Comment by Xuroth** [comment]
The way I found to do this is a couple of tweaks. First, when creating the node that you want to style (for its parent connection), add a new property:
```js
{
...
parentConnector: {}
}```
where `parentConnector` accepts the same styling as `connectors` (namely, the sub-property `style` object).

Then, in Treant.js, around line 910 you'll see where the node sets its parent connector style.
```js
connLine = this._R.path(pathString);
                this.connectionStore[treeNode.id] = connLine;

                // don't show connector arrows por pseudo nodes
                if (treeNode.pseudo) {
                    delete parent.connStyle.style['arrow-end'];
                }
                if (parent.pseudo) {
                    delete parent.connStyle.style['arrow-start'];
                }
// Add this block
                if (treeNode.parentConnector) {
                    console.log('has ParentConnector', treeNode);
                    connLine.attr(treeNode.parentConnector.style)
                } else {

                    connLine.attr(parent.connStyle.style); //This was the original line, now used as fallback
                }
// end
                if (treeNode.drawLineThrough || treeNode.pseudo) {
                    treeNode.drawLineThroughMe(hidePoint);
                }
```
 This allows you to dynamically pass in the desired connector styling for the node to its parent. I'm currently using this in a Content Tree system (family tree, bloodline, hierarchical tree, etc) and it works flawlessly thus far.

**Comment by niteshgupta89** [comment]
> The way I found to do this is a couple of tweaks. First, when creating the node that you want to style (for its parent connection), add a new property: ` { ... parentConnector: {} }` where `parentConnector` accepts the same styling as `connectors` (namely, the sub-property `style` object).
> 
> Then, in Treant.js, around line 910 you'll see where the node sets its parent connector style.
> 
> ```js
> connLine = this._R.path(pathString);
>                 this.connectionStore[treeNode.id] = connLine;
> 
>                 // don't show connector arrows por pseudo nodes
>                 if (treeNode.pseudo) {
>                     delete parent.connStyle.style['arrow-end'];
>                 }
>                 if (parent.pseudo) {
>                     delete parent.connStyle.style['arrow-start'];
>                 }
> // Add this block
>                 if (treeNode.parentConnector) {
>                     console.log('has ParentConnector', treeNode);
>                     connLine.attr(treeNode.parentConnector.style)
>                 } else {
> 
>                     connLine.attr(parent.connStyle.style); //This was the original line, now used as fallback
>                 }
> // end
>                 if (treeNode.drawLineThrough || treeNode.pseudo) {
>                     treeNode.drawLineThroughMe(hidePoint);
>                 }
> ```
> 
> This allows you to dynamically pass in the desired connector styling for the node to its parent. I'm currently using this in a Content Tree system (family tree, bloodline, hierarchical tree, etc) and it works flawlessly thus far.

Also, add this line in the reset function of the TreeNode.prototype
`this.parentConnector = (nodeStructure.parentConnector)? nodeStructure.parentConnector:null;`
