### ISSUE TITLE
Tree rendered weird at random times

### ISSUE THREAD

**Issue by micheleissa** [fperucic/treant-js#122]
Hello,
I have a weird situation and don't know why it is happening:
I'm loading the data from the server and showing it up in bootstrap modal, the first time everything works fine but the second time I try to display the same exact tree the nodes rendered in a messed up layout. I noted the x,y values used for left and top are calculated to different values the time the nodes rendered in the wrong spot. 

Correct Rendering:
![image](https://user-images.githubusercontent.com/16201881/41212502-04d281d8-6d04-11e8-8097-b16dda89986f.png)

Incorrect Rendering:
![image](https://user-images.githubusercontent.com/16201881/41212508-0ecd857a-6d04-11e8-9ea8-84a75c4cbb2d.png)

**Comment by fperucic** [comment]
try rendering the Tree on 'modal.shown' event, and make sure the DOM element you are trying to render it into has the correct width and height values

**Comment by micheleissa** [comment]
That seems to have solved the issue. Thank you so much
