### ISSUE TITLE
When there are a large number of duplicate pictures in the tree, the loading speed will be very slow.

### ISSUE THREAD

**Issue by bot960528** [fperucic/treant-js#124]
In my tree, each node has an image. Although the number of pictures is large, most of them are repetitive and actually fewer than ten.

The tree diagram will appear particularly slow when loaded.

I checked the "developer tools" found:

![_20180702155350](https://user-images.githubusercontent.com/19542659/42151644-35771886-7e10-11e8-92c0-7b2bad3a861c.png)

Each picture is followed by a timestamp parameter. I think it may be because of this parameter that causes the browser to identify the same picture as a different picture, resulting in repeated requests. As a result, the tree map is loaded too slowly.

Is there any way to solve this problem?

Thanks in advance.

**Comment by Hrnkas** [comment]
Such code is used when you want to circumvent the browser cache. It is usefull when the images change often, i.e. product images in a Webshop. However, I always use just the date, without time, so the cache works for one day and tomorrow it is invalid and has to be loaded again.
