### ISSUE TITLE
Collapsible + Node Link

### ISSUE THREAD

**Issue by bba278** [fperucic/treant-js#140]
In order to make a node collapsible AND having a link, I added a bit of jQuery code which appends a <p>Hide Children</p> to the 'collapse-switch' and depending on whether the node is opened or closed, I change the text. 

The above all works fine, except that in cases where a node is the **main root node** or **sub-tree root** node, the connectors from that node don't align/exit correctly from it but they rather come on top of the node (See photo snippets)

![image](https://user-images.githubusercontent.com/6471605/51198845-48d8e300-18ed-11e9-9d10-dd3796f7da82.png)

Would anybody be able to suggest a fix for that? 

Thanks

**Comment by bba278** [comment]
For anyone curious how I solved this -> applied the jQuery code to only child nodes and not the root ones

$(document).ready(function () {
      const collapseSwitch = $('a.node a.collapse-switch')
      collapseSwitch.text('Hide Children')
      collapseSwitch.addClass('hide-children')

      collapseSwitch.click(function () {
        const trgt = $(this)
        if (trgt.hasClass('show-children')) {
          trgt.text('Hide Children')
          trgt.removeClass('show-children')
          trgt.addClass('hide-children')
        } else {
          trgt.text('Show Children')
          trgt.removeClass('hide-children')
          trgt.addClass('show-children')
        }
      })
    })

**Comment by Method-Development** [comment]
I'm still getting the connecting line in the middle as shown above. How did you fix that portion?
