### ISSUE TITLE
Print Treant 

### ISSUE THREAD

**Issue by claudiopj** [fperucic/treant-js#15]
Two questions . Is there any way to print a large graphic that is generating a scroll ?

How to start a small graphic at the top of the div

**Comment by fperucic** [comment]
1. Make a large enoug cointainer with css before the chart is initalized and the scroll will not be applied
2. Make a smaller container before the chart initaialization

**Comment by claudiopj** [comment]
the problem is that my graphics are dynamically generated....
then I can not figure out if I have to build a large area or small

**Comment by claudiopj** [comment]
forgive me if I was not very specific in my question..
