### ISSUE TITLE
Two diagrams on same page

### ISSUE THREAD

**Issue by megatron0000** [fperucic/treant-js#19]
Seems like JSONconfig.getID() does not "reset" after completing a diagram. This led to problems when I tried to generate a second diagram in the same page (that is, create another Treant instance).

Actually, I modified this method to solve the issue _-_

**Comment by fperucic** [comment]
Hi, your question is valid, but why whould you want for `JSONconfig.getID` to reset?

**Comment by scrobbleme** [comment]
I'm able to use multiple trees on a page without any problem.

**Comment by leolr02** [comment]
scrobbleme, can you post your javascript code? I can't be able to initialize two diagrams in the same page

**Comment by scrobbleme** [comment]
@leolr02 Yes, see this page: http://stammbaum.dev.moewe.io/family-tree/persons/johann-caspar-goethe/
oder http://stammbaum.dev.moewe.io

There are 3 treant trees (even the single person card is one)

- For configuring the trees, the JSON structure is used (just look into the pages source)

Initialization is done with a simpe JavaScript:

```
jQuery(function (jQuery) {
    var charts = jQuery('.stammbaum-chart');
    charts.each(create_treant);

    function create_treant(index, element) {
        element = jQuery(element);
        var person = element.attr('data-person');
        element.data('treant', new Treant(window.stammbaum['person-hierarchy-' + person], align_graph));
    }

    function align_graph(tree) {
        var tree_container = jQuery(tree.drawArea);
        var wrapper = tree_container.parent();
        var element = tree_container.find('.node').last();
        tree.drawArea.scrollLeft = parseInt(element.css('left')) - ((wrapper.width() - element.width()) / 2);
    }
});
```

`align_graph` is just use to center the graph on the root node.

The main part is just muliple calls to `new Treant(configuration)`

So really nothing special.

**Comment by leolr02** [comment]
thanks is more clearly for me!!! , have a nice day  :+1:

**Comment by Mixone-FinallyHere** [comment]
This is not working for me :/

**Comment by scrobbleme** [comment]
@Mixone-FinallyHere What exactly is not working? Or better: What is happening, are there any (JavaScript) error? Do you have an example online.

**Comment by andrea-filoso** [comment]
I have this same problem.
```
<script>
	/* first tree  */
	config = { container: "#basic-example"};

	parent_node = {	text: { name: "First parent node" } };

	first_child = { parent: parent_node, text: { name: "First child" }};
	second_child = { parent: parent_node, text: { name: "Second child" }};
	
	simple_chart_config = [	config, parent_node, first_child, second_child ];

	var chart = new Treant( simple_chart_config );
	/* Here tree shows all 3 nodes */
	
	/* Second tree same container */
	config2 = { container: "#basic-example"};

	parent_node2 = { text: { name: "Second parent node" } };

	first_child2 = { parent: parent_node2, text: { name: "First child 2" }};
	second_child2 = { parent: parent_node2, text: { name: "Second child 2" }};

	simple_chart_config2 = [ config2, parent_node2, first_child2, second_child2 ];	

	chart = new Treant( simple_chart_config2 );
	/* Here tree shows only root node*/	
</script>
```

I think that bug could be in JSONconfig.getId() or in JSONconfig.findChildren(). 

```
findChildren: function(nodes) {
		var parents = [0]; // start with a a root node
		...
```

New Treant doesn't reset the i variable so when next Treant is created, the id of root node isn't 0 and findChildren() fails.
I hope this comment can help you.
