### ISSUE TITLE
Refresh chart

### ISSUE THREAD

**Issue by dusanstamen** [fperucic/treant-js#2]
How to refresh chart without page refresh? 

Thank you

**Comment by fperucic** [comment]
hi,
there isn't a fancy way to update a chart. However, I've just added a new method for destroying a chart  (see 497df0eb305ca65dd10d246f289ba9ec0a84b24f). So, a basic idea is to destroy an existing chart and recreate a new one in its place.

**Comment by safwannajib** [comment]
Hi, 
you can use the 
$.getScript( "Scripts/Treant.js" , function() {
// your chart code here
});

instead of load the the script in the page header
