### ISSUE TITLE
multiple relationship support

### ISSUE THREAD

**Issue by nirisarri** [fperucic/treant-js#24]
I want to be able to show multiple parent relationship.
It does not necessarily mean that every element of the tree has multiple parents, but it would be an interesting feature to add secondary connections to the tree, i.e. Employee X has a functional boos Y and an administrative boss Z 

```
           N
         /   \
       Z      Y
     /       /
    X-------
```

**Comment by PepaBosnis** [comment]
For creation such links I used jsPlumb but I see that it now not free. If it succeeds in creating in this project, I'll be happy.

**Comment by broszies** [comment]
I was (and am still) loking for a simple way to visualize a family tree based on database output. So being able to have two parents on the same level is a neccessity for me. Unfortunately, most JS or visualization libraries (google charts f.e.) fail to provide that. It seems to be a rather complicated problem, so far I have only seen one private website showing this, and they wont share their code :)
If it is possible with treant, but I am failing to see how, please let me know.

**Comment by dlgoodchild** [comment]
For one node to have multiple parents isn't possible with Treant, sorry.

**Comment by tamtom** [comment]
whyyyy! 😢

**Comment by jerchap** [comment]
Is this still the case? Is there any plan to implement this functionality?

**Comment by Extarys** [comment]
I would definitely buy you a beer ;)

**Comment by jerchap** [comment]
I wanted to use it to render a directed graph, which would require multiple parents for nodes.  I understand that it would complicate layout logic as you need to attempt to minimize overlap etc., so this may not actually be in the scope of the library.  A beer would definitely be in order if this functionality was introduced.

**Comment by aliqusai** [comment]
hey currently we have tree structure where when we click on a user i.e parent it shows the users under them like child but now we want to implement is there a parent's parent above it like when we click on parent it should show the user above it how this can be achieved can u please help
