### ISSUE TITLE
Non-ID-based Container?

### ISSUE THREAD

**Issue by machineghost** [fperucic/treant-js#26]
Currently Treant requires that users specify a container as a CSS ID selector (eg. `#basic-example`).  However, because you can only have a single element with a given ID on the page, IDs can become problematic in dynamic applications where charts are created "on the fly".

Would it be possible, given that you're already taking a CSS selector, to also accept a CSS class selector (ie. `.basic-example`)?

**Comment by dlgoodchild** [comment]
I've found the same issue. I'm going to adjust and make a pull request.

**Comment by dlgoodchild** [comment]
Pull-request was accepted, so this is now on the master branch.

**Comment by dlgoodchild** [comment]
This is now on master.

**Comment by dlgoodchild** [comment]
If you instantiate Treant using `new Treant( config, null, $ );` where `$` is jQuery, you can configure the container using a jQuery selector:
```
chart: {
	container: $( 'div.content > div.inner' )
	...
}
```
However if you instantiate without jQuery support `new Treant( config )`, you can now use either an ID or a class:
```
chart: {
	container: '.some-class'
	...
}
```
