### ISSUE TITLE
nodes with custom content, doesn't animate on collapse

### ISSUE THREAD

**Issue by rurikCL** [fperucic/treant-js#35]
I have an issue trying to animate custom nodes (filled with innerHTML property)
lines does animate correctly, but not the same for nodes. they just appear or dissapear. 

i have seted this config:
 animation: {
                nodeAnimation: "bounce",
                nodeSpeed: 700,
                connectorsAnimation: "bounce",
                connectorsSpeed: 700
            },

but nothing...
i look into the Treant.js code. and in the show method, there is a ( $) condition, but it is not entering.

**Comment by dlgoodchild** [comment]
The documentation needs, updated, which I'll be doing shortly.
You need to pass jQuery into the constructor of Treant.
```
var oConfig = { ... };
var oTree = new Treant( oConfig, null, $ );
```
You can replace null with a callback for when the tree completes. or you can specify a callback in the callback configuration option:
```
callback: { 'onTreeLoaded': function() {} }
```

**Comment by rurikCL** [comment]
Well. 
now i am receiving this error : TypeError: r.easing[this.easing] is not a function
