### ISSUE TITLE
Is there a way to collapse all nodes at once (toggle)

### ISSUE THREAD

**Issue by rurikCL** [fperucic/treant-js#36]
Is there any way to collapse all nodes at once via public method or a config to let only one node collapse at a time?

i added a caret icon to the <a> switch via:
`$("a.collapse-switch").html('< span class='glyphicon glyphicon-triangle-bottom' style='color:#fff'></span>')
            .on('click',function (e) {
                if($(this).find('span').hasClass('glyphicon-triangle-bottom')){
                    $(this).find('span').removeClass('glyphicon-triangle-bottom').addClass('glyphicon-triangle-top');
                }else{
                    $(this).find('span').removeClass('glyphicon-triangle-top').addClass('glyphicon-triangle-bottom');
                }
            });`

so, the idea is to hide all other collapsed branches, when one collapse.
i also tried calling the click event on other uncollapsed branches, but doesn't work.

this would be an interesting option to implement.

**Comment by dlgoodchild** [comment]
I don't really understand what you're doing or what you're asking.
1. You want to programmatically collapse the entire tree?
2. You want hide all other collapsed branches when one collapses? what do you mean hide? they are hidden then they are collapsed.

If you use the collapse configuration option and then click a parent node, all the children will be collapsed and "hidden", you then click the switch again and they are shown.

In a branch that I'm working on I added a .collapse() and .expand() function to the TreeNode class. Further I've added the ability (using jQuery) to get the TreeNode instance from a DOM element....here's an example:

```
onTreeLoaded: function() {
	var $oNodes = $( '.Treant .node' );
	$oNodes.on( 'click',
		function ( oEvent ) {
			if ( oEvent.target.nodeName == 'P' ) {
				var $oNode = $( this );
				$oNodes.removeClass( 'selected' );
				$oNode.addClass( 'selected' );

				var oMeta = $oNode.data( 'treenode' ).meta;
				$oNode.data( 'treenode' ).expand(); // could use .collapse()
			}
		}
	);
}
```
This example shows how I'm adding a .selected class to the node that I clicked, and removing that class from all other nodes, it then demonstrates programmatically expanding the state of all children.

There's an onCollapseFinished callback which you can use to then programmatically expand/collapse the children further if you wanted. I will do a pull request shortly with the .collapse/.expand functions (there are some new callbacks too which might be useful).

**Comment by rurikCL** [comment]
Sorry, i think i explained the wrong way, i misspelled the concept collapsed.

what i am trying to do. is to just allow a single branch  (childrens)  to shown at a time. 
i mean. When i click on a "uncollapsed" node, it will show all childrens, as it does now... but, what i want to do, is to hide "other" uncollapsed nodes, so only one node "uncollapsed" at a time. 

i will try with those useful callbacks you mention. 
It would be wonderful to have an updated documentation about this.

thx for your help and quick replies

**Comment by dlgoodchild** [comment]
Ah I think I understand now, you want it to collapse up and down the tree? as in collapse the parent nodes? You could do probably do that manually using an on-click even handler on the nodes and then using the `$( nodeEl ).data( 'treenode' )` you can now get hold of the TreeNode instance and manipulate the parent notes yourself. This piece of code I just referenced isn't available yet on this repo, I'll do a pull request tomorrow as I've just implemented some new stuff.

**Comment by OmniversalMax** [comment]
dlgoodchild,  I would like that capability as well.  Thanks!

**Comment by dlgoodchild** [comment]
It's not likely to be something I'd personally implement. It'd be quite complex to put that in, that's why I think you should do it externally using a combination of callbacks and normal click events, or you/someone can implement and do a pull request.

**Comment by kolin182** [comment]
Hi dlgoodchild, I would like that functionality also, What you mean with $( nodeEl ).data( 'treenode' ) ? I would implement that functionality but I'm not sure how can I get access to the treenodes from the other sibling nodes.. Can you tell me some details about that?


Thanks in advance.

**Comment by kolin182** [comment]
Ok, I found the way to make sure that only one branch is opened at the same time:

`callback: { 
                	onBeforeClickCollapseSwitch: function(nodeSwitch, event) {
                		//if the node is collapse we close all the neighbors

                		var any_to_close = false;
                		if (this.collapsed)
                		{
                			var current_node = this;
                			while (current_node.leftNeighborId)
                			{
                				current_node = current_node.dbGet(current_node.leftNeighborId);
                				if (current_node.collapsed)
                				{
                					any_to_close = true;
                				}
                				current_node.collapse();
                			}

                			var current_node = this;
                			while (current_node.rightNeighborId)
                			{
                				current_node = current_node.dbGet(current_node.rightNeighborId);
                				if (current_node.collapsed)
                				{
                					any_to_close = true;
                				}
                				current_node.collapse();
                			}

                			if (any_to_close)
                			{
                				var tree = this.Tree();
                				var current_node = this;
                				setTimeout(
									function() { // set the flag after the animation
										current_node.toggleCollapse();
									},
									( tree.CONFIG.animation.nodeSpeed > tree.CONFIG.animation.connectorsSpeed )?
										tree.CONFIG.animation.nodeSpeed:
										tree.CONFIG.animation.connectorsSpeed
								);
                			} else {
                				this.toggleCollapse();
                			}

                			
                		}`


It's not the best way, but it works perfectly.

**Comment by dlgoodchild** [comment]
Awesome, well done, and good use of the recent addition of callbacks; perfect example of their use!

**Comment by rurikCL** [comment]
Amazing!  great work .

**Comment by OmniversalMax** [comment]
kolin182, Where did you put your code?  I know it goes into treant.js, but I cannot figure out where to put it to get it to work.

Thanks!

**Comment by dlgoodchild** [comment]
The code, as shared above by @kolin182 goes in the chart config not in the treant source.

**Comment by kolin182** [comment]
Thanks @dlgoodchild, I did not see the mails because I was working with other mail, hope would be useful..
