### ISSUE TITLE
Search large chart

### ISSUE THREAD

**Issue by OmniversalMax** [fperucic/treant-js#40]
I have a very large chart.  Is there a way to search for a specific person or department?  Thanks!

**Comment by dlgoodchild** [comment]
Sorry, but person/department is implementation specific, not something that would go into a library.
Use jQuery and do a text :contains search: https://api.jquery.com/contains-selector/ specifically for your implementation.

**Comment by OmniversalMax** [comment]
Thanks, but I tried using that and it underlined everything in every node...is there a way to just highlight the node with the matching data, something like:

$("#search-criteria").on("keyup", function() {
    var g = $(this).val().toLowerCase();
	$( "node:contains(g)" ).css( "background-color", "yellow" );
});

**Comment by dlgoodchild** [comment]
You're mostly there, you've just got the jQuery selector wrong:
```
$( "#search-criteria" ).on( "keyup",
	function() {
		var g = $( this ).val().toLowerCase();
		$( '.node:contains('+g+')' ).css( "background-color", "yellow" );
	}
);
```
```

**Comment by OmniversalMax** [comment]
Mr. Goodchild,

I feel that we are very, very close, but when clicking on the search button it highlights a bunch of nodes that do not meet the criteria. 

 For example, I searched for my last name "keener" (and I am the only one in the company) and it highlighted all of the ones in the attached file.
![treantjs_2016-10-13_15-01-43](https://cloud.githubusercontent.com/assets/22690824/19365127/dfc6c370-9156-11e6-89cc-d9b1f8531b56.jpg)

Help me get this working and I will post the full code, plus some other tricks I figured out back to github.

Thanks!

**Comment by dlgoodchild** [comment]
The problem at the moment isn't with Treant it's now with the search code. I've not used jQuery's `contains` selector. You may find something useful here:
http://stackoverflow.com/questions/8746882/jquery-contains-selector-uppercase-and-lower-case-issue

The text within the `:contains( ... )` maybe needs wrapped in quotes. Do some tests to see what query sees as the `.text()` value for the node elements. It aggregates all the texts in the innerHTML, so maybe something in there is actually matching.
