### ISSUE TITLE
element.className.add is not a function

### ISSUE THREAD

**Issue by kingrollo** [fperucic/treant-js#41]
Hi,

I'm getting this error at line 177 of Treant.js. I'm guessing one of the dependencies hasn't wired itself up correctly. Could you possibly let me know what I'm missing?

Thanks!
r.

**Comment by dlgoodchild** [comment]
I've just pushed a new version which addresses this error and improves the non-jQuery support.
But, if you happen to have jQuery available on the page, pass it as the 3rd parameter to the Treant constructor.

**Comment by kingrollo** [comment]
Great - thanks very much!
