### ISSUE TITLE
Discontinuity Support?

### ISSUE THREAD

**Issue by ColmMathews** [fperucic/treant-js#44]
Hello, 
would firstly like to say the treant library is brilliant,
and secondly would like to ask if there is a utility to allow generation of trees with discontinuous scope? i.e What's in the image below, in particular figs c and e.
Thanks for your time, and best regards,
Colm.
![discontinuity](https://cloud.githubusercontent.com/assets/22682728/20530632/eff4278a-b0cb-11e6-9e4b-24d052bf382c.jpg)

**Comment by dlgoodchild** [comment]
Hi, this library doesn't support a tree layouts c and e, the rest can be achieved.
