### ISSUE TITLE
Dynamic images

### ISSUE THREAD

**Issue by V-LoZ** [fperucic/treant-js#45]
Hi, 

If dynamic image is used instead of static one, generated url is wrong. You can fix this with something like:

` // load event is not fired for cached images, force the load event` 
`if (image.src.indexOf('?')>0)`
`        image.src += "&" + new Date().getTime();`
` else`
`        image.src += "?" + new Date().getTime();`
`

**Comment by dlgoodchild** [comment]
Thanks, this has been implemented on `master`.
