### ISSUE TITLE
Multiple trees support

### ISSUE THREAD

**Issue by hegwin** [fperucic/treant-js#46]
Is there way or can you support to draw multiple trees?
My data structure is like a hierarchy, but it has more than one root points. It cannot work.

**Comment by fperucic** [comment]
yes, use the hiderootnode option. Than the main node will be hidden and first level children will become the new root nodes

**Comment by dlgoodchild** [comment]
@hegwin check out the examples/no-parent/index.html file...this is a fine example of @fperucic's answer
