### ISSUE TITLE
Tons of raphaeljs errors with animation config

### ISSUE THREAD

**Issue by altryne** [fperucic/treant-js#6]
![image](https://cloud.githubusercontent.com/assets/463317/12580444/711963a6-c438-11e5-8f55-4fb13a438837.png)

I wonder if you can point me to a direction of where these might come from.

They happen with this config : 

```
var config = {
                container: "#OrganiseChart8",
                /*levelSeparation:    70,
                siblingSeparation:  60,*/
                nodeAlign: "CENTER",
                animateOnInit: true,
                animateOnInitDelay: 500,
                node: {
                    collapsable: true
                },
                animation: {
                    nodeAnimation: "easeOutQuad",
                    nodeSpeed: 250,
                    connectorsAnimation: "bounce",
                    connectorsSpeed: 700
                },
                connectors: {
                    type: "step",
                    style: {
                        "stroke-width": 2,
                        "stroke": "#ccc",
                        "stroke-dasharray": "-", //"", "-", ".", "-.", "-..", ". ", "- ", "--", "- .", "--.", "--.."
                        "arrow-end": "classic-wide-long"
                    }
                }
            },
```

**Comment by fperucic** [comment]
hi,

i will try to test this as soon as possible. In the mean time, can you check if the same error occurs at past commits (ex: 2beaea880b69af3a020a415fede871732fee5627)

**Comment by altryne** [comment]
Yup, same thing
![image](https://cloud.githubusercontent.com/assets/463317/12581078/0d626812-c43d-11e5-8b75-466836b037f8.png)

Even worse, the nodes are hidden by the css by default for some reason...

**Comment by fperucic** [comment]
I took a look at those errors, they occur in Chrome when "arrow-end" property is set.
This can't be fixed in the scope of Treant they it needs to be examined in the Raphael library itself.
