### ISSUE TITLE
integrate Treant in a React Project?

### ISSUE THREAD

**Issue by ChiliChunk** [fperucic/treant-js#69]
Hello,
I red the doc and the example about how to create diagram with this library. It work with simple HTML file but I don't know how to manage the import and the use of Treant in a React component...
For the moment I install treant-js in my project using `npm install`.
I import treant in my componant like that: 
`import Treant from 'treant-js';`
I try to create the diagram with
 `var test = new Treant (diagramTemp);` 
but i got an error...
` _treantJs2.default is not a constructor`
I have no idea of what to do and I didn't find any help or docs about integrate Treant in React.
If someone have an idea to help me, it would be nice :) Thank you

**Comment by mrspinn** [comment]
Also interested in the solution. I managed to get Treat to import by using object destructuring when importing: ```import { Treant } from 'treant-js'```

Now I get ```ReferenceError: Raphael is not defined``` despite being having installed the Raphael node package and imported it accordingly. When I ```console.log(Raphael)``` I get the version number, but Treant is still unable to use Raphael

**Comment by mufaddalmw** [comment]
Same issue.

**Comment by aniel928** [comment]
I got it to work using this: https://stackoverflow.com/questions/44067112/how-to-integrate-treant-js-in-a-react-projet/56460743
