### ISSUE TITLE
I am trying to add a child node with two parent node (Mother ad Father and show relation with sibling nodes too)

### ISSUE THREAD

**Issue by digish** [fperucic/treant-js#8]
I could not do it from the examples shown 
if its possible an example would really help.

thanks

**Comment by fperucic** [comment]
hi,

such functionality is not possible at the moment. Maybe if you set the chart `rootOrientation` to `SOUTH` and set ` hideRootNode` to `true` you can achieve you goal.

**Comment by marcgetter** [comment]
Setting the rootOrientation to south will only work if there are only parents and no children.  I'd like to have a normal chart with children then reverse the tree starting at the root node to show the parents.
