### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by guilhermecgs** [fperucic/treant-js#94]
Hi Folks,

Is it possible to draw a circular dependency?

Example   
"d" is "a" parent
"c" is "d" parent
"a" is "c" parent

![image](https://user-images.githubusercontent.com/8465337/33183078-90c29c9e-d05d-11e7-9e37-73196bc540fd.png)

**Comment by dlgoodchild** [comment]
This is not possible with this library, sorry.

**Comment by siddht5** [comment]
@guilhermecgs  If you need similar feature asap then you have to use go.js,but it requires license. Check this https://gojs.net/latest/samples/navigation.html  for the time being.

As my issue sort of https://github.com/fperucic/treant-js/issues/96  kind of is similar to yours and can be implemented by same so I would try to add this feature.

**Comment by TonyDobbs** [comment]
@guilhermecgs Thank you for the tip! I started building a tree using treant, and then realized this limitation. looks like we are switching to go.js!
